sudo: false
language: python
dist: trusty
matrix:
  include:
    #
    # Python 3.5 testing
    #
    # lint
    - python: "3.5"
      env: TOX_POSARGS="-e lint"

    # doctest
    - python: "3.5"
      env: TOX_POSARGS="-e doctest"

    # core
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core"

    # backends
    - python: "3.5"
      env: TOX_POSARGS="-e py35-backend-pycryptodome"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-backend-pysha3"

    #
    # Python 3.6 testing
    #
    # core
    - python: "3.6"
      env: TOX_POSARGS="-e py36-core"

    # backends
    - python: "3.6"
      env: TOX_POSARGS="-e py36-backend-pycryptodome"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-backend-pysha3"

    #
    # pypy3 testing
    #
    # core
    - python: "pypy3.5"
      env: TOX_POSARGS="-e pypy3-core"

    # backends
    - python: "pypy3.5"
      env: TOX_POSARGS="-e pypy3-backend-pycryptodome"

cache:
  - pip: true
install:
  - travis_retry pip install pip setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - python --version
  - pip --version
  - pip freeze
script:
  - tox $TOX_POSARGS
