version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  docs:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: docs
  py37-lint:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-lint
  py37-core:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-core
  py37-backend-pysha3:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backend-pysha3
  py37-backend-pycryptodome:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backend-pycryptodome
  py38-lint:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-lint
  py38-core:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-core
  py38-backend-pysha3:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backend-pysha3
  py38-backend-pycryptodome:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backend-pycryptodome
  py39-lint:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-lint
  py39-core:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-core
  py39-backend-pysha3:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backend-pysha3
  py39-backend-pycryptodome:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backend-pycryptodome
  py310-lint:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-lint
  py310-core:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-core
  py310-backend-pysha3:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backend-pysha3
  py310-backend-pycryptodome:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backend-pycryptodome
  pypy3-core:
    <<: *common
    docker:
      - image: pypy
        environment:
          TOXENV: pypy3-core
  pypy3-backend-pycryptodome:
    <<: *common
    docker:
      - image: pypy
        environment:
          TOXENV: pypy3-backend-pycryptodome
workflows:
  version: 2
  test:
    jobs:
      - docs
      - py37-lint
      - py37-core
      - py37-backend-pysha3
      - py37-backend-pycryptodome
      - py38-lint
      - py38-core
      - py38-backend-pysha3
      - py38-backend-pycryptodome
      - py39-lint
      - py39-core
      - py39-backend-pysha3
      - py39-backend-pycryptodome
      - py310-lint
      - py310-core
      - py310-backend-pysha3
      - py310-backend-pycryptodome
      - pypy3-core
      - pypy3-backend-pycryptodome
